### ISSUE TITLE
Strange null ptr crash want to have log for it if it happens again

### ISSUE THREAD

**Issue by ryanrampage1** [SpartaHack/SpartaHack2016-Android#36]
02-02 16:44:41.982 5636-5636/com.spartahack.spartahack2016 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: com.spartahack.spartahack2016, PID: 5636
                                                                             java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setVisibility(int)' on a null object reference
                                                                                 at com.example.spartahack.spartahack2016.Fragment.HelpFragment.setRecyclerViewSections(HelpFragment.java:175)
                                                                                 at com.example.spartahack.spartahack2016.Fragment.HelpFragment.access$100(HelpFragment.java:37)
                                                                                 at com.example.spartahack.spartahack2016.Fragment.HelpFragment$1.done(HelpFragment.java:118)
                                                                                 at com.example.spartahack.spartahack2016.Fragment.HelpFragment$1.done(HelpFragment.java:86)
                                                                                 at com.parse.ParseTaskUtils$2$1.run(ParseTaskUtils.java:115)
                                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by ryanrampage1** [comment]
fixed with null check aka bandaid
